name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Setup credentials
      run: | 
        mkdir -p ~/.pub-cache 
        cat <<EOF > ~/.pub-cache/credentials.json
        {
          "accessToken":"${{ secrets.DART_ACCESS_TOKEN }}",
          "refreshToken":"${{ secrets.DART_REFRESH_TOKEN }}",
          "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
          "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
          "expiration":1585908637521
        }
        EOF
    - name: Publish package
      run: pub publish -f
